[tool.poetry]
name = "ganho-capital"
version = "0.1.0"
description = "Projeto com o objetivo de implementar um programa de linha de comando que calcula o imposto a ser pago sobre lucros ou prejuizos de operacoes no mercado financeiro de acoes"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^7.3.1"
pre-commit = "^3.3.1"
coverage = "^7.2.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
