name: Linter

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 -

    - name: Install project dependencies
      run: poetry install

    - name: Run black check
      run: poetry run black --check .

    - name: Run flake8 check
      run: poetry run flake8 --config=.flake8 --count .

    - name: Run mypy check
      run: poetry run mypy system

    - name: Run isort check
      run: poetry run isort . -c
