name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código-fonte
      uses: actions/checkout@v2

    - name: Configurar ambiente Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Instalar Poetry
      run: pip install poetry

    - name: Instalar dependências do projeto
      run: poetry install

    - name: Executar testes com pytest
      run: poetry run pytest
